# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: root

development:
  <<: *default
  database: todo_app.dev


#test:
#  <<: *default
#  database: todo_app.test

#production:
#  <<: *default
#  database: db/production.sqlite3

test:
  adapter: postgresql
   encoding: unicode
   pool: 5
